---
- name: Copying a file. 
  hosts: webservers
  become: true


  tasks:
  - name: Copying html file into hosts.
    copy:
            src: /home/charan/index.html
            dest: /var/www/html/
            mode: 0777
            owner: charan

...



