---
- name: Installing Httpd webserver and Deploy web application in the server.
  hosts: webservers
  become: true

  tasks:
  - name: Installing Httpd in RedHat Family.
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
 
      
  - name: Installing Apche in Debian Family
    apt:
      name: apache2
      state: installed
    when: ansible_os_family == "Debian"

  - name: Starting Services.
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: Starting services in Debian servers.
    service: 
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: Copying the Web file ino the nodes.
    copy:
      src: /home/charan/index.html 
      dest: /home/charan
      mode: 0644
      owner: charan
