---
- name: Installing  httpd. 
  hosts: webservers
  become: true
  tasks:
          - name: installing httpd webserver.
            yum:
                    name: httpd
                    state: installed

          - name: Starting services.
            service:
                    name: httpd
                    state: started

