---
- name: Uninstalling  httpd. 
  hosts: webservers
  become: true
  tasks:
  - name: Stpping services before uninstallation.
    service:
      name: httpd
      state: stopped

  - name: uninstall Httpd server.
    yum:
      name: httpd
      state: absent

  - name: Uninstalling Git.
    yum: 
      name: git
      state: absent

... 

