---
- name: Installing  httpd using handlers if notify macthed. 
  hosts: webservers
  become: true


  tasks:
  - name: installing httpd webserver.
    yum:
      name: httpd
      state: installed
    notify: Starting services.

  handlers:
          - name: Starting services.
            service:
                    name: httpd
                    state: started

